[NO_TASK] | Builds | Update build after start build
andrespaez90/BitriseApp pull request #3
Opened 2020-10-07 00:30 UTC by AndresUrregoC

2020-10-07 00:39 UTC, andrespaez90 requested changes

2020-10-07 00:39 UTC, andrespaez90 commented on app/src/main/java/com/bitrise/app/viewModels/builds/BuildsViewModel.kt
> +        get() = savedStateHandle.get<AppModel>(KEY_CURRENT_APP_MODEL)
No deberia preguntar al staeHandle siempre en un get, deberia hacerlo en el init del viewModel, si este valor no es null se guarda asi el currentAppModel no tiene que ser null

2020-10-07 00:39 UTC, andrespaez90 commented on app/build.gradle
> -    implementation 'androidx.navigation:navigation-fragment:2.3.0'
Porque se borra esta dependencia?

2020-10-07 00:44 UTC, AndresUrregoC commented on app/build.gradle
> -    implementation 'androidx.navigation:navigation-fragment:2.3.0'
Ya tiene la de ktx

2020-10-07 00:45 UTC, AndresUrregoC commented on app/src/main/java/com/bitrise/app/viewModels/builds/BuildsViewModel.kt
> +        get() = savedStateHandle.get<AppModel>(KEY_CURRENT_APP_MODEL)
Sería moverlo a donde se llame, pero es hacer lo mismo, y lo del null es el savestateHandle que lo devuelve así

2020-10-07 00:53 UTC, andrespaez90 commented on app/src/main/java/com/bitrise/app/viewModels/builds/BuildsViewModel.kt
> +        get() = savedStateHandle.get<AppModel>(KEY_CURRENT_APP_MODEL)
Claro pero se garantiza que el currentAppModel nunca es null

2020-11-06 02:08 UTC, closed without merging

2020-11-06 02:08 UTC, andrespaez90 commented
abandoned